src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ClientRepository::class)]
class Client
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'clients')]
    private ?User $user_id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $company_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $contact_person = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $contact_email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $contact_phone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $website_url = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $last_contact_date = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pref_contact_method = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $notes = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $creation_date = null;

    #[ORM\OneToMany(mappedBy: 'client', targetEntity: Project::class)]
    private Collection $projects;

    #[ORM\OneToMany(mappedBy: 'client', targetEntity: Billing::class)]
    private Collection $billings;

    public function __toSTring()
    {
        return $this->getUserId()->getFullName() . " - " . $this->company_name;
    }

    public function __construct()
    {
        $this->projects = new ArrayCollection();
        $this->billings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): static
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getCompanyName(): ?string
    {
        return $this->company_name;
    }

    public function setCompanyName(?string $company_name): static
    {
        $this->company_name = $company_name;

        return $this;
    }

    public function getContactPerson(): ?string
    {
        return $this->contact_person;
    }

    public function setContactPerson(?string $contact_person): static
    {
        $this->contact_person = $contact_person;

        return $this;
    }

    public function getContactEmail(): ?string
    {
        return $this->contact_email;
    }

    public function setContactEmail(?string $contact_email): static
    {
        $this->contact_email = $contact_email;

        return $this;
    }

    public function getContactPhone(): ?string
    {
        return $this->contact_phone;
    }

    public function setContactPhone(?string $contact_phone): static
    {
        $this->contact_phone = $contact_phone;

        return $this;
    }

    public function getWebsiteUrl(): ?string
    {
        return $this->website_url;
    }

    public function setWebsiteUrl(?string $website_url): static
    {
        $this->website_url = $website_url;

        return $this;
    }

    public function getLastContactDate(): ?\DateTimeImmutable
    {
        return $this->last_contact_date;
    }

    public function setLastContactDate(?\DateTimeImmutable $last_contact_date): static
    {
        $this->last_contact_date = $last_contact_date;

        return $this;
    }

    public function getPrefContactMethod(): ?string
    {
        return $this->pref_contact_method;
    }

    public function setPrefContactMethod(?string $pref_contact_method): static
    {
        $this->pref_contact_method = $pref_contact_method;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(?string $notes): static
    {
        $this->notes = $notes;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeImmutable
    {
        return $this->creation_date;
    }

    public function setCreationDate(?\DateTimeImmutable $creation_date): static
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    /**
     * @return Collection<int, Project>
     */
    public function getProjects(): Collection
    {
        return $this->projects;
    }

    public function addProject(Project $project): static
    {
        if (!$this->projects->contains($project)) {
            $this->projects->add($project);
            $project->setClient($this);
        }

        return $this;
    }

    public function removeProject(Project $project): static
    {
        if ($this->projects->removeElement($project)) {
            // set the owning side to null (unless already changed)
            if ($project->getClient() === $this) {
                $project->setClient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Billing>
     */
    public function getBillings(): Collection
    {
        return $this->billings;
    }

    public function addBilling(Billing $billing): static
    {
        if (!$this->billings->contains($billing)) {
            $this->billings->add($billing);
            $billing->setClient($this);
        }

        return $this;
    }

    public function removeBilling(Billing $billing): static
    {
        if ($this->billings->removeElement($billing)) {
            // set the owning side to null (unless already changed)
            if ($billing->getClient() === $this) {
                $billing->setClient(null);
            }
        }

        return $this;
    }
}

src/Entity/Page.php
<?php

namespace App\Entity;

use App\Repository\PageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PageRepository::class)]
class Page
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $heading = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $url = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $featured_image = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $page_content = null;

    #[ORM\Column(nullable: true)]
    private ?bool $content_first = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_service = null;

    #[ORM\ManyToMany(targetEntity: Section::class, inversedBy: 'pages')]
    private Collection $sections;

    public function __toString(): string
    {
        return (string) $this->heading;
    }

    public function __construct()
    {
        $this->sections = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHeading(): ?string
    {
        return $this->heading;
    }

    public function setHeading(?string $heading): static
    {
        $this->heading = $heading;

        return $this;
    }

    public function getMetaTitle(): ?string
    {
        return $this->meta_title;
    }

    public function setMetaTitle(?string $meta_title): static
    {
        $this->meta_title = $meta_title;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->meta_description;
    }

    public function setMetaDescription(?string $meta_description): static
    {
        $this->meta_description = $meta_description;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): static
    {
        $this->url = $url;

        return $this;
    }

    public function getFeaturedImage(): ?string
    {
        return $this->featured_image;
    }

    public function setFeaturedImage(?string $featured_image): static
    {
        $this->featured_image = $featured_image;

        return $this;
    }

    public function getPageContent(): ?string
    {
        return $this->page_content;
    }

    public function setPageContent(?string $page_content): static
    {
        $this->page_content = $page_content;

        return $this;
    }

    public function isContentFirst(): ?bool
    {
        return $this->content_first;
    }

    public function setContentFirst(?bool $content_first): static
    {
        $this->content_first = $content_first;

        return $this;
    }

    public function isIsService(): ?bool
    {
        return $this->is_service;
    }

    public function setIsService(?bool $is_service): static
    {
        $this->is_service = $is_service;

        return $this;
    }

    /**
     * @return Collection<int, Section>
     */
    public function getSections(): Collection
    {
        return $this->sections;
    }

    public function addSection(Section $section): static
    {
        if (!$this->sections->contains($section)) {
            $this->sections->add($section);
        }

        return $this;
    }

    public function removeSection(Section $section): static
    {
        $this->sections->removeElement($section);

        return $this;
    }
}

src/Entity/SEO.php
<?php

namespace App\Entity;

use App\Repository\SEORepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SEORepository::class)]
class SEO
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $heading = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $logo_path = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $keywords = null;

    public function __toString(): string
    {
        return (string) $this->heading;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHeading(): ?string
    {
        return $this->heading;
    }

    public function setHeading(?string $heading): static
    {
        $this->heading = $heading;

        return $this;
    }

    public function getMetaTitle(): ?string
    {
        return $this->meta_title;
    }

    public function setMetaTitle(?string $meta_title): static
    {
        $this->meta_title = $meta_title;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->meta_description;
    }

    public function setMetaDescription(?string $meta_description): static
    {
        $this->meta_description = $meta_description;

        return $this;
    }

    public function getLogoPath(): ?string
    {
        return $this->logo_path;
    }

    public function setLogoPath(?string $logo_path): static
    {
        $this->logo_path = $logo_path;

        return $this;
    }

    public function getKeywords(): ?string
    {
        return $this->keywords;
    }

    public function setKeywords(?string $keywords): static
    {
        $this->keywords = $keywords;

        return $this;
    }
}

src/Entity/Theme.php
<?php

namespace App\Entity;

use App\Repository\ThemeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ThemeRepository::class)]
class Theme
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pri_color = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $sec_color = null;

    #[ORM\ManyToOne(inversedBy: 'themes')]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'themes')]
    private ?Template $template = null;

    #[ORM\OneToMany(targetEntity: Invoice::class, mappedBy: 'theme')]
    private Collection $invoices;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    public function __construct()
    {
        $this->invoices = new ArrayCollection();
    }

    public function __toString(): string
    {
        return (string) $this->getName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPriColor(): ?string
    {
        return $this->pri_color;
    }

    public function setPriColor(?string $pri_color): static
    {
        $this->pri_color = $pri_color;

        return $this;
    }

    public function getSecColor(): ?string
    {
        return $this->sec_color;
    }

    public function setSecColor(?string $sec_color): static
    {
        $this->sec_color = $sec_color;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getTemplate(): ?Template
    {
        return $this->template;
    }

    public function setTemplate(?Template $template): static
    {
        $this->template = $template;

        return $this;
    }

    /**
     * @return Collection<int, Invoice>
     */
    public function getInvoices(): Collection
    {
        return $this->invoices;
    }

    public function addInvoice(Invoice $invoice): static
    {
        if (!$this->invoices->contains($invoice)) {
            $this->invoices->add($invoice);
            $invoice->setTheme($this);
        }

        return $this;
    }

    public function removeInvoice(Invoice $invoice): static
    {
        if ($this->invoices->removeElement($invoice)) {
            // set the owning side to null (unless already changed)
            if ($invoice->getTheme() === $this) {
                $invoice->setTheme(null);
            }
        }

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): static
    {
        $this->name = $name;

        return $this;
    }
}

templates/index/index.html.twig
{% extends 'base.html.twig' %}

{% block page %}
{% if page is not null %}

	{% set sortedSections = page.sections|sort((a, b) => a.priority <=> b.priority) %}

	{% for section in sortedSections %}	
	{{ include('sections/' ~ section.templatePath) }}
	{% endfor %}

{% endif %}
{% endblock %}

templates/index/it.html.twig
{% extends 'inv_base.html.twig' %}

{% block stylesheets %}
<style>
.invoice_style3 .invoice-table thead th {
    background: -webkit-linear-gradient(top, {{invoice.theme.priColor}} -35.51%, #000000 196.64%);
    background: linear-gradient(180deg, {{invoice.theme.priColor}} -35.51%, #000000 196.64%);
}
{% if invoice.invoiceItems|length > 4 %}
@media print {
    body {
    zoom: 95%; /* Adjust the percentage as needed to fit content on one page */
  }
}
{% endif %}
</style>
{% endblock %}
{% block body %}
<body class="it-template">
{% set logo_width = invoice.client.company.logoType == 'square' ? 150 : 300 %}
{% set max_height = invoice.client.company.logoType == 'square' ? 150 : 70 %}

    <!--[if lte IE 9]>
    	<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->


    <!--********************************
   		Code Start From Here 
	******************************** -->

    <div class="invoice-container-wrap">
        <div class="invoice-container">
            <main>
                <!--==============================
Invoice Area
==============================-->
                <div class="th-invoice invoice_style3">
                    <div class="download-inner" id="download_section">
                        <!--==============================
	Header Area
==============================-->
                        <header class="th-header header-layout2">
                            <div class="row align-items-start justify-content-between">
                                <div class="col-auto">
                                    <div class="header-logo">
                                        <a href="{{invoice.client.company.website}}"><img style="max-width:{{logo_width}}px;max-height:{{max_height}}px" src="/invoices/images/{{invoice.client.company.logoPath}}" alt="Joe SEO Invoice Generator"></a>
                                    </div>
                                </div>
                                <div class="col-auto">
                                    <h1 class="big-title">{{invoice.type}}</h1>
                                </div>
                            </div>
                        </header>
                        <div class="row justify-content-between mb-30 mt-40 pt-3">
                            <div class="col-auto">
                                {% if invoice.type == 'invoice' %}
                                <div class="invoice-left">
                                    <b>Invoiced To:</b>
                                    <address>
                                        {{invoice.client.name}} <br>
                                        {{invoice.client.contactDetails}} <br>
                                        {{invoice.client.address}} <br>
                                        {{invoice.client.email}} <br>
                                        {{invoice.client.phone}} <br>
                                    </address>
                                </div>
                                {% endif %}
                            </div>
                            <div class="col-auto">
                                <b>From:</b>
                                <address>
                                    {{invoice.client.company.companyName}}<br>
                                    {{invoice.client.company.email}}<br>
                                    {{invoice.client.company.phone}}<br>
                                    {{invoice.client.company.website}}<br>
                                </address>

                                <p class="invoice-number mb-2 pb-1"><b>{{invoice.type|title}} No: </b>#{{invoice.invoiceNumber}}</p>
                                <p class="invoice-date"><b>Date: </b>{{invoice.date|date('d-m-Y')}}</p>
                                {% if invoice.type == 'invoice' %}<p class="invoice-date"><b>Due Date: </b>{{invoice.dueDate|date('d-m-Y')}}</p>{% endif %}
                            </div>
                        </div>
                        <table class="invoice-table td-big table-stripe-column">
                            <thead>
                                <tr>
                                    <th>SL</th>
                                    <th>Service Description</th>
                                    <th>Price</th>
                                    <th>Qty</th>
                                    <th>Total</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for item in invoice.invoiceItems %}
                                <tr>
                                    <td>{{loop.index}}</td>
                                    <td>{{item.description}}</td>
                                    <td>{{item.unitPrice|number_format}}</td>
                                    <td>{{item.quantity}}</td>
                                    <td>{{item.totalAmount|number_format}}</td>
                                </tr>
                            {% endfor %}
                            {% if invoice.invoiceItems|length < 3 %}                            
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                            {% endif %}
                            </tbody>
                        </table>
                        <div class="row justify-content-between">
                            <div class="col-auto">
                                {% if invoice.type == 'invoice' %}
                                <div class="invoice-left text-white mb-30">
                                    <b>Payment Info:</b>
                                    <p style="max-width:280px;" class="mb-0">{{invoice.paymentInfo|nl2br}}</p>
                                </div>
                                {% endif %}
                                <div class="invoice-left text-white">
                                    <b>Terms & Conditions</b>
                                    <p style="max-width:280px;" class="mb-0">{{invoice.termsConditions|nl2br}}</p>
                                </div>
                            </div>
                            <div class="col-auto">
                            {% if invoice.taxType == 'inclusive' %}
                                <table class="total-table">
                                    <tr>
                                        <th>Sub Total:</th>
                                        <td>KSh {{invoice.totalAmount|number_format}}</td>
                                    </tr>
                                    <tr>
                                        <th>Tax:</th>
                                        <td>KSh {{invoice.tax|number_format}}</td>
                                    </tr>
                                    <tr>
                                        <th>Discount:</th>
                                        <td>KSh {{invoice.discount|number_format}}</td>
                                    </tr>
                                    {% set finalAmount = (invoice.totalAmount - invoice.tax) - invoice.discount %}
                                    <tr>
                                        <th>Total:</th>
                                        <td>KSh {{finalAmount|number_format}}</td>
                                    </tr>
                                </table>
                            {% else %}
                                <table class="total-table">
                                    <tr>
                                        <th>Sub Total:</th>
                                        <td>KSh {{invoice.totalAmount|number_format}}</td>
                                    </tr>                                    
                                    <tr>
                                        <th>Tax:</th>
                                        <td>KSh {{invoice.tax|number_format}}</td>
                                    </tr>
                                    <tr>
                                        <th>Discount:</th>
                                        <td>KSh {{invoice.discount|number_format}}</td>
                                    </tr>
                                    {% set finalAmount = (invoice.totalAmount + invoice.tax) - invoice.discount %}
                                    <tr>
                                        <th>Total:</th>
                                        <td>KSh {{finalAmount|number_format}}</td>
                                    </tr>
                                </table>
                            {% endif %}
                                <div class="invoice-note2 mt-25">
                                    <p style="width:200px;" class="mb-0"><b>NOTE:</b> {{invoice.notes|nl2br}}.</p>
                                </div>
                            </div>
                        </div>
                        <div class="body-shape1">
                            <svg width="416" height="139" viewBox="0 0 416 139" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M366.015 139H0L61.7157 0H416L366.015 139Z" fill="url(#paint0_linear_307_104)" />
                                <defs>
                                    <linearGradient id="paint0_linear_307_104" x1="280.311" y1="-75.7221" x2="280.311" y2="120.434" gradientUnits="userSpaceOnUse">
                                        <stop offset="0.1344" stop-color="{{invoice.theme.secColor}}" />
                                        <stop offset="1" stop-color="{{invoice.theme.priColor}}" />
                                    </linearGradient>
                                </defs>
                            </svg>
                        </div>
                        <div class="body-shape2">
                            <svg width="498" height="405" viewBox="0 0 498 405" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M309.963 405H0V0H498L309.963 405Z" fill="url(#paint0_linear_307_1187)" />
                                <defs>
                                    <linearGradient id="paint0_linear_307_1187" x1="335.564" y1="-220.629" x2="335.564" y2="350.906" gradientUnits="userSpaceOnUse">
                                        <stop offset="0.1344" stop-color="{{invoice.theme.secColor}}" />
                                        <stop offset="1" stop-color="{{invoice.theme.priColor}}" />
                                    </linearGradient>
                                </defs>
                            </svg>
                        </div>
                    </div>
                    {% include ('sections/buttons.html.twig') %}
                </div>


            </main>
        </div>
    </div>
    <!-- Invoice Conainter End -->
{% endblock %}

templates/index/page.html.twig
{% extends 'base.html.twig' %}
{% block meta_description %}{{page.metaDescription}}{% endblock %}
{% block meta_title %}{{page.metaTitle }}{% endblock %}
{% block page %}

	{% set sortedSections = page.sections|sort((a, b) => a.priority <=> b.priority) %}
    {% if page.pageContent|length > 1 %}
        {% include('sections/variable_banner.html.twig') %}
        {% if page.contentFirst %}
            {% include ('sections/service.html.twig') %}
            {% for section in sortedSections %}	
            {{ include('sections/' ~ section.templatePath) }}
            {% endfor %}
        {% else %}
            {% for section in sortedSections %}	
            {{ include('sections/' ~ section.templatePath) }}
            {% endfor %}
            {% include ('sections/service.html.twig') %}
        {% endif %}
    {% else %}
        {% for section in sortedSections %}
            {{ include('sections/' ~ section.templatePath) }}
        {% endfor %}    
    {% endif %}

{% endblock %}

templates/index/profile.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}  {% endblock %}
{% block page %}

{% endblock %}

templates/index/service.html.twig
{% extends 'base.html.twig' %}
{% block meta_description %}{{page.metaDescription}}{% endblock %}
{% block meta_title %}{{page.metaTitle }}{% endblock %}
{% block page %}

	{% set sortedSections = page.sections|sort((a, b) => a.priority <=> b.priority) %}
    {% include('sections/service_banner.html.twig') %}
    {% if page.contentFirst %}
        {% include ('sections/service.html.twig') %}
        {% for section in sortedSections %}	
        {{ include('sections/' ~ section.templatePath) }}
        {% endfor %}
    {% else %}
        {% for section in sortedSections %}	
        {{ include('sections/' ~ section.templatePath) }}
        {% endfor %}
        {% include ('sections/service.html.twig') %}
    {% endif %}

{% endblock %}

templates/index/test2.html.twig
{{dump(statements)}}