src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Repository\BlogRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BlogRepository::class)]
class Blog
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'blogs')]
    private ?User $author = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $content = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $publication_date = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $status = null;

    #[ORM\ManyToMany(targetEntity: BlogCategory::class, inversedBy: 'blogs')]
    private Collection $categories;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $tags = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image_url = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $video_embed = null;

    #[ORM\OneToMany(mappedBy: 'blog', targetEntity: BlogComment::class)]
    private Collection $blogComments;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $slug = null;

    public function __toSTring()
    {
        return $this->title;
    }

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->categories = new ArrayCollection();
        $this->blogComments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getPublicationDate(): ?\DateTimeImmutable
    {
        return $this->publication_date;
    }

    public function setPublicationDate(?\DateTimeImmutable $publication_date): static
    {
        $this->publication_date = $publication_date;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): static
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection<int, BlogCategory>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(BlogCategory $category): static
    {
        if (!$this->categories->contains($category)) {
            $this->categories->add($category);
        }

        return $this;
    }

    public function removeCategory(BlogCategory $category): static
    {
        $this->categories->removeElement($category);

        return $this;
    }

    public function getTags(): ?string
    {
        return $this->tags;
    }

    public function setTags(?string $tags): static
    {
        $this->tags = $tags;

        return $this;
    }

    public function getImageUrl(): ?string
    {
        return $this->image_url;
    }

    public function setImageUrl(?string $image_url): static
    {
        $this->image_url = $image_url;

        return $this;
    }

    public function getVideoEmbed(): ?string
    {
        return $this->video_embed;
    }

    public function setVideoEmbed(?string $video_embed): static
    {
        $this->video_embed = $video_embed;

        return $this;
    }

    /**
     * @return Collection<int, BlogComment>
     */
    public function getBlogComments(): Collection
    {
        return $this->blogComments;
    }

    public function addBlogComment(BlogComment $blogComment): static
    {
        if (!$this->blogComments->contains($blogComment)) {
            $this->blogComments->add($blogComment);
            $blogComment->setBlog($this);
        }

        return $this;
    }

    public function removeBlogComment(BlogComment $blogComment): static
    {
        if ($this->blogComments->removeElement($blogComment)) {
            // set the owning side to null (unless already changed)
            if ($blogComment->getBlog() === $this) {
                $blogComment->setBlog(null);
            }
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Repository\BlogCategoryRepository;
use App\Repository\BlogRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\SeoService;

class BlogController extends AbstractController
{
    public function __construct(private SeoService $seoService){}

    #[Route('/blog', name: 'app_blog')]
    public function index(BlogRepository $blogRepo, BlogCategoryRepository $blogCategoryRepo): Response
    {
        $recentBlogs = $blogRepo->findBy(
            [],
            ['id' => 'DESC'],
            10
        );

        $posts = $blogRepo->findByStatus('published');

        $this->seoService->setTitle('Handy SEO Tips For Your Business | Joe SEO')
            ->setDescription('Easy-to-understand SEO and GBP tips to make your business stand out on search engines. Manage your back-end like a pro!')
            ->setKeywords('SEO services Nairobi, Best SEO companies in Nairobi, Affordable SEO Kenya, SEO for small businesses Nairobi, Kenyan SEO agency, Increase website traffic Kenya, Improve Google ranking Nairobi, SEO consultant Nairobi, Local SEO Nairobi, E-commerce SEO Nairobi, Content marketing for SEO Nairobi, Link building services Kenya, Mobile SEO Nairobi, Technical SEO audit Kenya, Website optimization Nairobi, Google My Business optimization Kenya')
            ->setOgTitle('Handy SEO Tips For Your Business')
            ->setOgDescription('Easy-to-understand SEO and GBP tips to make your business stand out on search engines. Manage your back-end like a pro!')
            ->setOgImage('https://joeseo.co.ke/img/joe-seo-logo.jpg')
            ->setOgUrl('https://joeseo.co.ke/')
            ->setOgType('website');
        
        return $this->render('blog/index.html.twig', [
            'meta_tags' => $this->seoService->generateMetaTags(),
            'posts' => $posts,
            'blogCategories' => $blogCategoryRepo->findAll(),
            'recentBlogs' => $recentBlogs,
        ]);
    }

    #[Route('/blog/category/{category}', name: 'app_blog_category')]
    public function indexCategory(BlogRepository $blogRepo, BlogCategoryRepository $blogCategoryRepo, $category): Response
    {
        $recentBlogs = $blogRepo->findBy(
            [],
            ['id' => 'DESC'],
            10
        );

        $posts = $blogRepo->createQueryBuilder('b')
            ->innerJoin('b.categories', 'c')
            ->where('c.category_name = :categoryName')
            ->andWhere('b.status = :status')
            ->setParameter('categoryName', $category)
            ->setParameter('status', 'published')
            ->orderBy('b.id', 'DESC')
            ->getQuery()
            ->getResult();

        $this->seoService->setTitle('Handy SEO Tips For Your Business | ' . str_replace('_', ' ', $category))
            ->setDescription('Easy-to-understand ' . str_replace('_', ' ', $category) . ' tips to make your business stand out on search engines. Manage your back-end like a pro!')
            ->setKeywords('SEO services Nairobi, Best SEO companies in Nairobi, Affordable SEO Kenya, SEO for small businesses Nairobi, Kenyan SEO agency, Increase website traffic Kenya, Improve Google ranking Nairobi, SEO consultant Nairobi, Local SEO Nairobi, E-commerce SEO Nairobi, Content marketing for SEO Nairobi, Link building services Kenya, Mobile SEO Nairobi, Technical SEO audit Kenya, Website optimization Nairobi, Google My Business optimization Kenya')
            ->setOgTitle('Handy SEO Tips For Your Business | ' . str_replace('_', ' ', $category))
            ->setOgDescription('Easy-to-understand ' . str_replace('_', ' ', $category) . ' tips to make your business stand out on search engines. Manage your back-end like a pro!')
            ->setOgImage('https://joeseo.co.ke/img/joe-seo-logo.jpg')
            ->setOgUrl('https://joeseo.co.ke/')
            ->setOgType('website');

        return $this->render('blog/index.html.twig', [
            'meta_tags' => $this->seoService->generateMetaTags(),
            'posts' => $posts,
            'recentBlogs' => $recentBlogs,
            'blogCategories' => $blogCategoryRepo->findAll(),
        ]);
    }

    #[Route('/blog/{slug}', name: 'blog_detail')]
    public function show(BlogRepository $blogRepo, BlogCategoryRepository $blogCategoryRepo, $slug): Response
    {
        $recentBlogs = $blogRepo->findBy(
            [],
            ['id' => 'DESC'],
            10
        );

        $post = $blogRepo->findOneBySlug($slug);

        $this->seoService->setTitle($post->getTitle())
            ->setDescription(substr(strip_tags($post->getContent()), 0,150) . "...")
            ->setKeywords('SEO services Nairobi, Best SEO companies in Nairobi, Affordable SEO Kenya, SEO for small businesses Nairobi, Kenyan SEO agency, Increase website traffic Kenya, Improve Google ranking Nairobi, SEO consultant Nairobi, Local SEO Nairobi, E-commerce SEO Nairobi, Content marketing for SEO Nairobi, Link building services Kenya, Mobile SEO Nairobi, Technical SEO audit Kenya, Website optimization Nairobi, Google My Business optimization Kenya')
            ->setOgTitle($post->getTitle())
            ->setOgDescription(substr(strip_tags($post->getContent()), 0,150) . "...")
            ->setOgImage('https://joeseo.co.ke/img/joe-seo-logo.jpg')
            ->setOgUrl('https://joeseo.co.ke/')
            ->setOgType('website');

        return $this->render('blog/detail.html.twig', [
            'meta_tags' => $this->seoService->generateMetaTags(),
            'post' => $post,
            'recentBlogs' => $recentBlogs,
            'blogCategories' => $blogCategoryRepo->findAll(),
        ]);
    }
}

templates/blog/index.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}  {% endblock %}

{% block page %}
        <!-- Page Title -->
        <div class="page-title animatedBackground">
            <div class="container">
                <h1>Updates And Tips From JoeSEO</h1>
                <ul>
                    <li><a href="{{path('app_index')}}">Home</a></li>
                    <li class="dot-divider"></li>
                    <li>Blog</li>
                </ul>
            </div>
            
            <div class="bg-pattern"><img src="/img/joeseo.jpg" alt="pattern"></div>
        </div>
        <!-- End Page Title -->

        <!-- Blog Area -->
        <section class="blog-area ptb-100">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-12">
                        <div class="row">
                            {% for post in posts|reverse %}
                            <div class="col-lg-6 col-md-6">
                                <div class="single-blog-post">
                                    <a href="{{path('blog_detail', {'slug': post.slug})}}" class="blog-image"><img src="/site/images/blog_images/{{post.imageUrl}}" alt="blog"></a>
                                    
                                    <div class="blog-post-content">
                                        <h2 style="font-size:1.1em"><span>{% for category in post.categories %} {{ category|replace({'_': ' '}) ~ ' ' }} {% endfor %}</span><h2>
                                        <h4><a href="{{path('blog_detail', {'slug': post.slug})}}">{{post.title}}</a></h4>
                                        <p>{{post.content|striptags|slice(0,200)|raw|nl2br}}...</p>
                                        <a href="{{path('blog_detail', {'slug': post.slug })}}" class="read-more-btn">Read More</a>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}

                        </div>
                    </div>

                    <div class="col-lg-4 col-md-12">
                        <div class="side-bar mb-0">
                            <div class="widget-box search-box">
                                <form>
                                    <input type="text" placeholder="Search here..." class="form-control">
                                    <button type="submit"><i class="icofont-search-2"></i></button>
                                </form>
                            </div>

                            <div class="widget-box categories-box">
                                <h3 class="title">Categories</h3>

                                <ul>
                                {% for category in blogCategories %}
                                    <li><a href="{{path('app_blog_category', {'category': category.categoryName })}}"><i class="icofont-dotted-right"></i> {{category.categoryName|replace({'_': ' '})}}</a></li>
                                {% endfor %}
                                </ul>
                            </div>

                            {# <div class="widget-box tags-box">
                                <h3 class="title">Tags</h3>

                                <ul>
                                    <li><a href="#">Design</a></li>
                                    <li><a href="#">Branding</a></li>
                                    <li><a href="#">Entertainment</a></li>
                                    <li><a href="#">Arts</a></li>
                                    <li><a href="#">Blog Post</a></li>
                                    <li><a href="#">Seo Analysis</a></li>
                                    <li><a href="#">Marketing</a></li>
                                    <li><a href="#">Email Marketing</a></li>
                                </ul>
                            </div> #}

                            <div class="widget-box recent-post-box mb-0">
                                <h3 class="title">Recent Post</h3>

                                <ul>
                                    {% for blog in recentBlogs %}
                                    <li>
                                        <div class="recent-post-thumb">
                                            <a href="#"><img src="/site/images/blog_images/{{blog.imageUrl}}" alt="pic"></a>
                                        </div>

                                        <div class="recent-post-desc">
                                            <h3><a href="#">{{blog.title}}</a></h3>
                                            <span class="date">{{blog.publicationDate|date('jS M Y')}}</span>
                                        </div>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Blog Area -->
        
{% endblock %}