src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Repository\BlogRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BlogRepository::class)]
class Blog
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'blogs')]
    private ?User $author = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $content = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $publication_date = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $status = null;

    #[ORM\ManyToMany(targetEntity: BlogCategory::class, inversedBy: 'blogs')]
    private Collection $categories;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $tags = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image_url = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $video_embed = null;

    #[ORM\OneToMany(mappedBy: 'blog', targetEntity: BlogComment::class)]
    private Collection $blogComments;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $slug = null;

    public function __toSTring()
    {
        return $this->title;
    }

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->categories = new ArrayCollection();
        $this->blogComments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getPublicationDate(): ?\DateTimeImmutable
    {
        return $this->publication_date;
    }

    public function setPublicationDate(?\DateTimeImmutable $publication_date): static
    {
        $this->publication_date = $publication_date;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): static
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection<int, BlogCategory>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(BlogCategory $category): static
    {
        if (!$this->categories->contains($category)) {
            $this->categories->add($category);
        }

        return $this;
    }

    public function removeCategory(BlogCategory $category): static
    {
        $this->categories->removeElement($category);

        return $this;
    }

    public function getTags(): ?string
    {
        return $this->tags;
    }

    public function setTags(?string $tags): static
    {
        $this->tags = $tags;

        return $this;
    }

    public function getImageUrl(): ?string
    {
        return $this->image_url;
    }

    public function setImageUrl(?string $image_url): static
    {
        $this->image_url = $image_url;

        return $this;
    }

    public function getVideoEmbed(): ?string
    {
        return $this->video_embed;
    }

    public function setVideoEmbed(?string $video_embed): static
    {
        $this->video_embed = $video_embed;

        return $this;
    }

    /**
     * @return Collection<int, BlogComment>
     */
    public function getBlogComments(): Collection
    {
        return $this->blogComments;
    }

    public function addBlogComment(BlogComment $blogComment): static
    {
        if (!$this->blogComments->contains($blogComment)) {
            $this->blogComments->add($blogComment);
            $blogComment->setBlog($this);
        }

        return $this;
    }

    public function removeBlogComment(BlogComment $blogComment): static
    {
        if ($this->blogComments->removeElement($blogComment)) {
            // set the owning side to null (unless already changed)
            if ($blogComment->getBlog() === $this) {
                $blogComment->setBlog(null);
            }
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

}

src/Entity/Page.php
<?php

namespace App\Entity;

use App\Repository\PageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PageRepository::class)]
class Page
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $heading = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $meta_description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $url = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $featured_image = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $page_content = null;

    #[ORM\Column(nullable: true)]
    private ?bool $content_first = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_service = null;

    #[ORM\ManyToMany(targetEntity: Section::class, inversedBy: 'pages')]
    private Collection $sections;

    public function __toString(): string
    {
        return (string) $this->heading;
    }

    public function __construct()
    {
        $this->sections = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHeading(): ?string
    {
        return $this->heading;
    }

    public function setHeading(?string $heading): static
    {
        $this->heading = $heading;

        return $this;
    }

    public function getMetaTitle(): ?string
    {
        return $this->meta_title;
    }

    public function setMetaTitle(?string $meta_title): static
    {
        $this->meta_title = $meta_title;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->meta_description;
    }

    public function setMetaDescription(?string $meta_description): static
    {
        $this->meta_description = $meta_description;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): static
    {
        $this->url = $url;

        return $this;
    }

    public function getFeaturedImage(): ?string
    {
        return $this->featured_image;
    }

    public function setFeaturedImage(?string $featured_image): static
    {
        $this->featured_image = $featured_image;

        return $this;
    }

    public function getPageContent(): ?string
    {
        return $this->page_content;
    }

    public function setPageContent(?string $page_content): static
    {
        $this->page_content = $page_content;

        return $this;
    }

    public function isContentFirst(): ?bool
    {
        return $this->content_first;
    }

    public function setContentFirst(?bool $content_first): static
    {
        $this->content_first = $content_first;

        return $this;
    }

    public function isIsService(): ?bool
    {
        return $this->is_service;
    }

    public function setIsService(?bool $is_service): static
    {
        $this->is_service = $is_service;

        return $this;
    }

    /**
     * @return Collection<int, Section>
     */
    public function getSections(): Collection
    {
        return $this->sections;
    }

    public function addSection(Section $section): static
    {
        if (!$this->sections->contains($section)) {
            $this->sections->add($section);
        }

        return $this;
    }

    public function removeSection(Section $section): static
    {
        $this->sections->removeElement($section);

        return $this;
    }
}

src/Entity/Pricing.php
<?php

namespace App\Entity;

use App\Repository\PricingRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PricingRepository::class)]
class Pricing
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pricing_category = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 0, nullable: true)]
    private ?string $price = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $currency = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $billing_cycle = null;

    #[ORM\ManyToMany(targetEntity: Service::class, inversedBy: 'pricings')]
    private Collection $services;

    public function __toSTring()
    {
        return $this->getServiceName();
    }

    public function __construct()
    {
        $this->services = new ArrayCollection();
    }

    public function getServiceName(): string
    {
        return $this->pricing_category . "-" . $this->billing_cycle;
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPricingCategory(): ?string
    {
        return $this->pricing_category;
    }

    public function setPricingCategory(?string $pricing_category): static
    {
        $this->pricing_category = $pricing_category;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(?string $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    public function setCurrency(?string $currency): static
    {
        $this->currency = $currency;

        return $this;
    }

    public function getBillingCycle(): ?string
    {
        return $this->billing_cycle;
    }

    public function setBillingCycle(?string $billing_cycle): static
    {
        $this->billing_cycle = $billing_cycle;

        return $this;
    }

    /**
     * @return Collection<int, Service>
     */
    public function getServices(): Collection
    {
        return $this->services;
    }

    public function addService(Service $service): static
    {
        if (!$this->services->contains($service)) {
            $this->services->add($service);
        }

        return $this;
    }

    public function removeService(Service $service): static
    {
        $this->services->removeElement($service);

        return $this;
    }
}

src/Entity/Section.php
<?php

namespace App\Entity;

use App\Repository\SectionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SectionRepository::class)]
class Section
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $template_path = null;

    #[ORM\Column(nullable: true)]
    private ?int $priority = null;

    #[ORM\ManyToMany(targetEntity: Page::class, mappedBy: 'sections')]
    private Collection $pages;

    public function __construct()
    {
        $this->pages = new ArrayCollection();
    }

    public function __toString(): string
    {
        return (string) $this->description;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getTemplatePath(): ?string
    {
        return $this->template_path;
    }

    public function setTemplatePath(?string $template_path): static
    {
        $this->template_path = $template_path;

        return $this;
    }

    public function getPriority(): ?int
    {
        return $this->priority;
    }

    public function setPriority(?int $priority): static
    {
        $this->priority = $priority;

        return $this;
    }

    /**
     * @return Collection<int, Page>
     */
    public function getPages(): Collection
    {
        return $this->pages;
    }

    public function addPage(Page $page): static
    {
        if (!$this->pages->contains($page)) {
            $this->pages->add($page);
            $page->addSection($this);
        }

        return $this;
    }

    public function removePage(Page $page): static
    {
        if ($this->pages->removeElement($page)) {
            $page->removeSection($this);
        }

        return $this;
    }
}

templates/sections/audit_request_sm.html.twig
<!-- Analysis Area -->
    <div class="container">
        <div class="analysis-form">
            <h2><span>{{ render_content('audit-request-title', 'Free SEO Analysis') }}</span></h2>
            {{ form_start(form) }}
                <div class="form-group">
                    {{ form_widget(form.name, {'attr': {'class': 'form-control', 'placeholder':'name'}}) }}
                </div>
                
                <div class="form-group">
                    {{ form_widget(form.email, {'attr': {'class': 'form-control', 'placeholder':'email'}}) }} 
                </div>
                
                <div class="form-group">
                    {{ form_widget(form.phone, {'attr': {'class': 'form-control', 'placeholder':'phone'}}) }} 
                </div>
                
                <div class="form-group">
                    {{ form_widget(form.website, {'attr': {'class': 'form-control', 'placeholder':'website'}}) }}  
                </div>
                
                <div class="form-group">
                    {{ form_widget(form.company_name, {'attr': {'class': 'form-control', 'placeholder':'company_name'}}) }}
                </div>
                <button type="submit" class="btn btn-primary">{{ render_content('audit-request-form-cta', 'Get Free Report') }}</button>
            {{ form_end(form) }}
        </div>

        <div class="analysis-text">
            <span>{{ render_content('audit-request-pre-title', 'Free SEO Analysis') }}</span>
            <h3 style="font-size:1.3em">{{ render_content('audit-request-h3', 'Get a free video of an SEO audit for <a class="colored-underline">your website</a>.') }}</h3>
            {{ render_content('audit-request-text', '<p>Complete the form to receive a complimentary video guide detailing the essential steps to optimize your website for superior SEO performance. Unlock actionable insights and boost your online visibility!:<p>') }}
        </div>
        <p>
        <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
            {{ render_content('what-you-get', 'What You Will Get') }}
        </a>
        </p>
        <div class="collapse" id="collapseExample">
        <div class="card card-body">
            {{ render_content('what-you-get-list', ' 
            <ul>
                <li style="color:black">Personalized Analysis: Learn about the specific strengths and weaknesses of your website with a personalized SEO analysis.</li>
                <li style="color:black">Tailored Recommendations: Receive tailored recommendations based on your website\'s current status to enhance its SEO performance.</li>
                <li style="color:black">Technical SEO Guidance: Receive guidance on technical aspects to ensure your website meets search engine standards.</li>
                <li style="color:black">Competitor Comparison: Understand how your website stacks up against competitors and identify opportunities for improvement.</li>
                <li style="color:black">User Experience Recommendations: Get tips on improving the overall user experience to keep visitors engaged and satisfied.</li>
            </ul>
            ') }}
        </div>
        </div>

    </div>
<!-- End Analysis Area -->

templates/sections/blog_area.html.twig
        <!-- Blog Area -->
        <section class="blog-area ptb-100">
            <div class="container">
                <div class="section-title">
                    <h2><span>{{ render_content('blog-area-title', 'Our News') }}</span></h2>
                    <h3>{{ render_content('blog-area-subtitle', 'Latest Blog Posts') }}</h3>
                    <p>{{ render_content('blog-area-text', 'Get tips on how to keep on top of search results, and manage your Google Business Profile.') }}</p>
                    <a href="{{path('app_blog')}}" class="read-more-btn">{{ render_content('blog-area-cta', 'View More News.') }}</a>
                </div>
                
                <div class="row">
                    <div class="blog-slider owl-carousel owl-theme">
                        {% for blog in blogs %}
                        <div class="col-lg-12 col-md-12">
                            <div class="single-blog-item" style="background-image: url(/site/images/blog_images/{{blog.imageUrl}});">
                                <h2 style="font-size:1.1em"><span>{% for category in blog.categories %} {{ category|replace({'_': ' '}) ~ ' ' }} {% endfor %}</span></h2>
                                <h4><a href="#">{{blog.title}}</a></h4>
                                <p> {{blog.content|striptags|slice(0,200)|raw|nl2br}}...</p>
                                
                                <a href="{{path('blog_detail', {'slug': blog.slug})}}" title="Read More" class="link-btn"><i class="icofont-stylish-right"></i></a>
                            </div>
                        </div>
                        {% endfor %}
                        
                    </div>
                </div>
            </div>
        </section>
        <!-- End Blog Area -->

templates/sections/cta.html.twig
        <!-- CTA Area -->
        <section class="funfacts-area ptb-100">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-12">
                        <div class="fun-fact">
                            <h3><span class="count">{{ render_content('cta-title', 'We Are Ready. <br/><br/> Are You?') }}</span></h3>
                        </div>
                    </div>
                    
                    <div class="col-lg-6 col-md-12">
                        <div class="fun-fact">
                            <a href="tel:0765356000" class="btn mt-5 btn-secondary btn-lg">{{ render_content('cta-cta', 'Call Us Now') }}</a>
                        </div>
                    </div>
                    
                </div>
            </div>
        </section>
        <!-- End CTA Area -->

templates/sections/page-sidebar.html.twig
                <div class="sidebar mt-5">
                    <h3>{{ render_content('sidebar-title', 'Explore Our Services') }}</h3>
                    <ul>
                        <li><a href="{{ path('local_seo') }}">Local SEO Services</a></li>
                        <li><a href="{{path('app_invoice_index')}}">Free Invoice Builder</a></li>
                        <li><a href="{{path('keywords_add')}}">Free Content Keyword Density Checker</a></li>
                        <li><a href="#">Content Marketing</a></li>
                        <li><a href="{{path('app_page', {'page': 'technical-seo-in-kenya'})}}">Technical SEO</a></li>
                        <li><a href="#">SEO Audit Services</a></li>
                    </ul>

                    <h3>Learn More</h3>
                    <ul>
                        <li><a href="{{ path('app_blog') }}">Our Blog</a></li>
                        <li><a href="{{ path('app_project') }}">Projects</a></li>
                        <li><a href="#">FAQs</a></li>
                    </ul>

                    <h3>{{ render_content('sidebar-contact-heading', 'Contact Us') }}</h3>
                    <p>{{ render_content('side-bar-text', 'Have questions or need further assistance? Reach out to us:') }}</p>
                    <p>Email: <a href="mailto:contact@joeseo.co.ke">{{ setting is not null and setting.emailAddress is not empty ? setting.emailAddress : 'contact@joeseo.co.ke' }}</a></p>
                    <p>Phone: <a href="tel:0765356000">{{ setting is not null and setting.phoneNumber is not empty ? setting.phoneNumber : '0765356000' }}</a></p>

                    <a href="{{path('app_page', {'page': 'contact'})}}" class="btn btn-primary mt-3">{{ render_content('sidebar-cta-text', 'Contact Us') }}</a>
                </div>

templates/sections/pricing.html.twig
        <!-- Pricing Area -->
        <section class="pricing-area ptb-100 bg-fbf9f8">
            <div class="container">
                <div class="section-title">
                    <h2><span>{{ render_content('pricing-heading', 'Our SEO Services Pricing In Nairobi') }}</span></h2>
                    <h3 style="font-size:1.3em">{{ render_content('pricing-subheading', 'No hidden charges, choose your plan') }}</h3>
                    <p>{{ render_content('pricing-text', 'We enjoy adapting our strategies to offer you the best solutions according to your unique needs.') }}</p>
                    <a href="tel:{{ setting is not null and setting.phoneNumber is not empty ? setting.phoneNumber : '0765356000' }}" class="read-more-btn">{{ render_content('pricing-first-cta', 'Call Us Now.') }}</a>
                </div>
                
                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <div class="tab-slider-nav">
                            <ul class="tab-slider-tabs">
                                <li class="tab-slider-trigger active" rel="monthly">Monthly</li>
                                <li class="tab-slider-trigger" rel="yearly">Yearly</li>
                            </ul>
                        </div>
                    
                        <div class="tab-slider-container">
                            <div id="monthly" class="tab-slider-body">
                                <div class="row">
                                  {% for pricing in pricings %}
                                    <div class="col-lg-4 col-md-6">
                                        <div class="pricingTable">
                                            <div class="pricingTable-header">
                                                <h3 class="title">{{pricing.pricingCategory}}</h3>
                                                <div class="price-value">{{pricing.currency}} {{pricing.price|number_format(0)}} <span>/per month</span></div>
                                            </div>
                                            
                                            <ul class="pricing-content">
                                                {% for service in pricing.services|sort((a, b) => a.position <=> b.position) %}
                                                <li>{{service.serviceName}}</li>
                                                {% endfor %}
                                            </ul>
                                            
                                            <a href="tel:{{ setting is not null and setting.phoneNumber is not empty ? setting.phoneNumber : '0765356000' }}" class="btn btn-primary">{{ render_content('main-cta', 'Call Now') }}</a>
                                        </div>
                                    </div>
                                  {% endfor %}
                                    
                                </div>
                            </div>

                            {# <div id="yearly" class="tab-slider-body">
                                <div class="row">
                                    <div class="col-lg-4 col-md-6">
                                        <div class="pricingTable">
                                            <div class="pricingTable-header">
                                                <h3 class="title">Basic</h3>
                                                <div class="price-value">$59.99 <span>/per year</span></div>
                                            </div>
                                            
                                            <ul class="pricing-content">
                                                <li>Managment & Marketing</li>
                                                <li>SEO Optimization</li>
                                                <li>25 Analytics Campaign</li>
                                                <li>1,300Change Keywords</li>
                                                <li>25 Social Media Reviews</li>
                                                <li>1 Free Optimization</li>
                                                <li>24/7 Support</li>
                                            </ul>
                                            
                                            <a href="#" class="btn btn-primary">Buy Now</a>
                                        </div>
                                    </div>
                                    
                                    <div class="col-lg-4 col-md-6">
                                        <div class="pricingTable">
                                            <div class="pricingTable-header">
                                                <h3 class="title">Ultra</h3>
                                                <div class="price-value">$79.99 <span>/per year</span></div>
                                            </div>
                                            
                                            <ul class="pricing-content">
                                                <li>Managment & Marketing</li>
                                                <li>SEO Optimization</li>
                                                <li>25 Analytics Campaign</li>
                                                <li>1,300Change Keywords</li>
                                                <li>25 Social Media Reviews</li>
                                                <li>1 Free Optimization</li>
                                                <li>24/7 Support</li>
                                            </ul>
                                            
                                            <a href="#" class="btn btn-primary">Buy Now</a>
                                        </div>
                                    </div>
                                    
                                    <div class="col-lg-4 col-md-6 offset-lg-0 offset-md-3">
                                        <div class="pricingTable">
                                            <div class="pricingTable-header">
                                                <h3 class="title">Pro</h3>
                                                <div class="price-value">$99.99 <span>/per year</span></div>
                                            </div>
                                            
                                            <ul class="pricing-content">
                                                <li>Managment & Marketing</li>
                                                <li>SEO Optimization</li>
                                                <li>25 Analytics Campaign</li>
                                                <li>1,300Change Keywords</li>
                                                <li>25 Social Media Reviews</li>
                                                <li>1 Free Optimization</li>
                                                <li>24/7 Support</li>
                                            </ul>
                                            
                                            <a href="#" class="btn btn-primary">Buy Now</a>
                                        </div>
                                    </div>
                                </div>
                            </div> #}
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="rocket"><img src="{{ asset('site/assets/img/rocket.png') }}" alt="rocket"></div>
        </section>
        <!-- End Pricing Area -->

templates/sections/service.html.twig
<style>
    .project-details-area a {
        color: #ff6347!important;
    }
</style>
        <!-- Project Details Area -->
        <section class="project-details-area mt-5">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">

                        <div class="project-details">
                            <div class="row">
                                <div class="col-lg-8 col-md-7">
                                    <div id="table-of-contents"></div>
                                    {{ page.pageContent|raw }}
                                </div>

                                <div class="col-lg-4 col-md-5">
                                    <div class="project-info">
                                        {% if page.featuredImage is not null %}
                                            <div class="project-img">
                                                <img src="{{asset('site/images/page_images/' ~ page.featuredImage ) }}" alt="{{ page.heading }}">
                                            </div>
                                        {% endif %}                                    
                                        <h2 class="mt-5">Other Services</h2>
                                        <ul>
                                        {% for service in services %}
                                            <li><a href="{{path('app_page', {'page': service.url})}}"><i class="far fa-long-arrow-right"></i>{{ service.heading }}</a></li>
                                        {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- End Project Details Area -->