src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ClientRepository::class)]
class Client
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'clients')]
    private ?User $user_id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $company_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $contact_person = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $contact_email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $contact_phone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $website_url = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $last_contact_date = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pref_contact_method = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $notes = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $creation_date = null;

    #[ORM\OneToMany(mappedBy: 'client', targetEntity: Project::class)]
    private Collection $projects;

    #[ORM\OneToMany(mappedBy: 'client', targetEntity: Billing::class)]
    private Collection $billings;

    public function __toSTring()
    {
        return $this->getUserId()->getFullName() . " - " . $this->company_name;
    }

    public function __construct()
    {
        $this->projects = new ArrayCollection();
        $this->billings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): static
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getCompanyName(): ?string
    {
        return $this->company_name;
    }

    public function setCompanyName(?string $company_name): static
    {
        $this->company_name = $company_name;

        return $this;
    }

    public function getContactPerson(): ?string
    {
        return $this->contact_person;
    }

    public function setContactPerson(?string $contact_person): static
    {
        $this->contact_person = $contact_person;

        return $this;
    }

    public function getContactEmail(): ?string
    {
        return $this->contact_email;
    }

    public function setContactEmail(?string $contact_email): static
    {
        $this->contact_email = $contact_email;

        return $this;
    }

    public function getContactPhone(): ?string
    {
        return $this->contact_phone;
    }

    public function setContactPhone(?string $contact_phone): static
    {
        $this->contact_phone = $contact_phone;

        return $this;
    }

    public function getWebsiteUrl(): ?string
    {
        return $this->website_url;
    }

    public function setWebsiteUrl(?string $website_url): static
    {
        $this->website_url = $website_url;

        return $this;
    }

    public function getLastContactDate(): ?\DateTimeImmutable
    {
        return $this->last_contact_date;
    }

    public function setLastContactDate(?\DateTimeImmutable $last_contact_date): static
    {
        $this->last_contact_date = $last_contact_date;

        return $this;
    }

    public function getPrefContactMethod(): ?string
    {
        return $this->pref_contact_method;
    }

    public function setPrefContactMethod(?string $pref_contact_method): static
    {
        $this->pref_contact_method = $pref_contact_method;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(?string $notes): static
    {
        $this->notes = $notes;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeImmutable
    {
        return $this->creation_date;
    }

    public function setCreationDate(?\DateTimeImmutable $creation_date): static
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    /**
     * @return Collection<int, Project>
     */
    public function getProjects(): Collection
    {
        return $this->projects;
    }

    public function addProject(Project $project): static
    {
        if (!$this->projects->contains($project)) {
            $this->projects->add($project);
            $project->setClient($this);
        }

        return $this;
    }

    public function removeProject(Project $project): static
    {
        if ($this->projects->removeElement($project)) {
            // set the owning side to null (unless already changed)
            if ($project->getClient() === $this) {
                $project->setClient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Billing>
     */
    public function getBillings(): Collection
    {
        return $this->billings;
    }

    public function addBilling(Billing $billing): static
    {
        if (!$this->billings->contains($billing)) {
            $this->billings->add($billing);
            $billing->setClient($this);
        }

        return $this;
    }

    public function removeBilling(Billing $billing): static
    {
        if ($this->billings->removeElement($billing)) {
            // set the owning side to null (unless already changed)
            if ($billing->getClient() === $this) {
                $billing->setClient(null);
            }
        }

        return $this;
    }
}

src/Entity/Project.php
<?php

namespace App\Entity;

use App\Repository\ProjectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProjectRepository::class)]
class Project
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'projects')]
    private ?Client $client = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $project_name = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $start_date = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $end_date = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $project_status = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2, nullable: true)]
    private ?string $budget = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $priority_level = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $project_type = null;

    #[ORM\ManyToOne(inversedBy: 'projects')]
    private ?User $project_manager = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $creation_date = null;

    #[ORM\OneToMany(mappedBy: 'project', targetEntity: Task::class)]
    private Collection $tasks;

    #[ORM\OneToMany(mappedBy: 'project', targetEntity: Keyword::class)]
    private Collection $keywords;

    #[ORM\OneToMany(mappedBy: 'project', targetEntity: Report::class)]
    private Collection $reports;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $project_image = null;

    #[ORM\OneToMany(mappedBy: 'project', targetEntity: Content::class)]
    private Collection $contents;

    #[ORM\OneToMany(mappedBy: 'project', targetEntity: Billing::class)]
    private Collection $billings;

    #[ORM\OneToMany(mappedBy: 'project', targetEntity: StrategyAdjustments::class)]
    private Collection $strategyAdjustments;

    #[ORM\OneToMany(mappedBy: 'project', targetEntity: Email::class)]
    private Collection $emails;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $project_description = null;

    public function __toSTring()
    {
        return $this->project_name;
    }

    public function __construct()
    {
        $this->tasks = new ArrayCollection();
        $this->keywords = new ArrayCollection();
        $this->reports = new ArrayCollection();
        $this->contents = new ArrayCollection();
        $this->billings = new ArrayCollection();
        $this->strategyAdjustments = new ArrayCollection();
        $this->emails = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): static
    {
        $this->client = $client;

        return $this;
    }

    public function getProjectName(): ?string
    {
        return $this->project_name;
    }

    public function setProjectName(?string $project_name): static
    {
        $this->project_name = $project_name;

        return $this;
    }

    public function getStartDate(): ?\DateTimeImmutable
    {
        return $this->start_date;
    }

    public function setStartDate(?\DateTimeImmutable $start_date): static
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeImmutable
    {
        return $this->end_date;
    }

    public function setEndDate(?\DateTimeImmutable $end_date): static
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getProjectStatus(): ?string
    {
        return $this->project_status;
    }

    public function setProjectStatus(?string $project_status): static
    {
        $this->project_status = $project_status;

        return $this;
    }

    public function getBudget(): ?string
    {
        return $this->budget;
    }

    public function setBudget(?string $budget): static
    {
        $this->budget = $budget;

        return $this;
    }

    public function getPriorityLevel(): ?string
    {
        return $this->priority_level;
    }

    public function setPriorityLevel(?string $priority_level): static
    {
        $this->priority_level = $priority_level;

        return $this;
    }

    public function getProjectType(): ?string
    {
        return $this->project_type;
    }

    public function setProjectType(?string $project_type): static
    {
        $this->project_type = $project_type;

        return $this;
    }

    public function getProjectManager(): ?User
    {
        return $this->project_manager;
    }

    public function setProjectManager(?User $project_manager): static
    {
        $this->project_manager = $project_manager;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeImmutable
    {
        return $this->creation_date;
    }

    public function setCreationDate(?\DateTimeImmutable $creation_date): static
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    /**
     * @return Collection<int, Task>
     */
    public function getTasks(): Collection
    {
        return $this->tasks;
    }

    public function addTask(Task $task): static
    {
        if (!$this->tasks->contains($task)) {
            $this->tasks->add($task);
            $task->setProject($this);
        }

        return $this;
    }

    public function removeTask(Task $task): static
    {
        if ($this->tasks->removeElement($task)) {
            // set the owning side to null (unless already changed)
            if ($task->getProject() === $this) {
                $task->setProject(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Keyword>
     */
    public function getKeywords(): Collection
    {
        return $this->keywords;
    }

    public function addKeyword(Keyword $keyword): static
    {
        if (!$this->keywords->contains($keyword)) {
            $this->keywords->add($keyword);
            $keyword->setProject($this);
        }

        return $this;
    }

    public function removeKeyword(Keyword $keyword): static
    {
        if ($this->keywords->removeElement($keyword)) {
            // set the owning side to null (unless already changed)
            if ($keyword->getProject() === $this) {
                $keyword->setProject(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Report>
     */
    public function getReports(): Collection
    {
        return $this->reports;
    }

    public function addReport(Report $report): static
    {
        if (!$this->reports->contains($report)) {
            $this->reports->add($report);
            $report->setProject($this);
        }

        return $this;
    }

    public function removeReport(Report $report): static
    {
        if ($this->reports->removeElement($report)) {
            // set the owning side to null (unless already changed)
            if ($report->getProject() === $this) {
                $report->setProject(null);
            }
        }

        return $this;
    }

    public function getProjectImage(): ?string
    {
        return $this->project_image;
    }

    public function setProjectImage(?string $project_image): static
    {
        $this->project_image = $project_image;

        return $this;
    }

    /**
     * @return Collection<int, Content>
     */
    public function getContents(): Collection
    {
        return $this->contents;
    }

    public function addContent(Content $content): static
    {
        if (!$this->contents->contains($content)) {
            $this->contents->add($content);
            $content->setProject($this);
        }

        return $this;
    }

    public function removeContent(Content $content): static
    {
        if ($this->contents->removeElement($content)) {
            // set the owning side to null (unless already changed)
            if ($content->getProject() === $this) {
                $content->setProject(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Billing>
     */
    public function getBillings(): Collection
    {
        return $this->billings;
    }

    public function addBilling(Billing $billing): static
    {
        if (!$this->billings->contains($billing)) {
            $this->billings->add($billing);
            $billing->setProject($this);
        }

        return $this;
    }

    public function removeBilling(Billing $billing): static
    {
        if ($this->billings->removeElement($billing)) {
            // set the owning side to null (unless already changed)
            if ($billing->getProject() === $this) {
                $billing->setProject(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, StrategyAdjustments>
     */
    public function getStrategyAdjustments(): Collection
    {
        return $this->strategyAdjustments;
    }

    public function addStrategyAdjustment(StrategyAdjustments $strategyAdjustment): static
    {
        if (!$this->strategyAdjustments->contains($strategyAdjustment)) {
            $this->strategyAdjustments->add($strategyAdjustment);
            $strategyAdjustment->setProject($this);
        }

        return $this;
    }

    public function removeStrategyAdjustment(StrategyAdjustments $strategyAdjustment): static
    {
        if ($this->strategyAdjustments->removeElement($strategyAdjustment)) {
            // set the owning side to null (unless already changed)
            if ($strategyAdjustment->getProject() === $this) {
                $strategyAdjustment->setProject(null);
            }
        }

        return $this;
    }

    /**

templates/project/detail.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}  
    <script type="application/ld+json">
        {
            "@context": "https://schema.org",
            "@type": "BreadcrumbList",
            "name": "{{ project.projectName }} - {{ project.projectType }}",
            "itemListElement": [
                {
                    "@type": "ListItem",
                    "position": 1,
                    "name": "Home Page",
                    "item": "https://joeseo.co.ke"
                },
                {
                    "@type": "ListItem",
                    "position": 2,
                    "name": "Projects",
                    "item": "https://joeseo.co.ke/projects"
                },
                {
                    "@type": "ListItem",
                    "position": 3,
                    "name": "{{ project.projectName }} - {{ project.projectType }}",
                    "item": "https://joeseo.co.ke/project/details/Cheza%20Music%20School"
                }
            ]
        }
    </script>

    <style>
         h2 {
            font-size: 2em;
            font-weight: bold;
            margin-bottom: 20px;
            text-align: center;
            position: relative;
        }
        h3 {
            font-size: 1.2em;
            font-weight: bold;
        }
        h2 span {
            background-color: #ff6d34;
            color: white;
            padding: 0 15px;
            position: relative;
            z-index: 1;
            text-transform: capitalize;
            font-size: 16px;
            font-weight: 400;
        }
        h2::after {
            content: '';
            display: block;
            width: 100%;
            height: 2px;
            background-color: #ff6d34;
            position: absolute;
            top: 50%;
            left: 0;
            z-index: 0;
        }
        .section-title p, .section-content p {
            font-size: 1.1em;
            line-height: 1.6;
        }
        .btn-primary {
            background-color: #ff6d34;
            border-color: #ff6d34;
        }
        .read-more-btn {
            margin-top: 10px;
            display: inline-block;
            background-color: #ff6d34;
            color: white;
            padding: 10px 20px;
            border-radius: 5px;
            text-decoration: none;
        }
        .read-more-btn:hover {
            background-color: #0056b3;
        }  
        section {
            padding:10px;
        }
    </style>

{% endblock %}
{% block page %}

        <!-- Page Title -->
        <div class="page-title animatedBackground">
            <div class="container">
                <h1>{{ project.projectName }} - {{ project.projectType }} | Joe SEO</h1>
                <ul>
                    <li><a href="{{path('app_index')}}">Home</a></li>
                    <li class="dot-divider"></li>
                    <li>Projects</li>
                    <li class="dot-divider"></li>
                    <li>{{ project.projectName }}</li>
                </ul>
            </div>
            
            <div class="bg-pattern"><img src="/img/joeseo.jpg" alt="pattern"></div>
        </div>
        <!-- End Page Title -->
                
        <!-- Project Details Area -->
        <section class="project-details-area ptb-100">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">

                        <div class="project-details">
                            <div class="row">
                                <div class="col-lg-8 col-md-7">
                                    <div class="project-img">
                                        <img src="/site/images/project_images/{{ project.projectImage }}" alt="photo">
                                    </div>

                                    <h2><span>Project Details</span></h2>
                                    {{ project.projectDescription | raw }}
                                </div>

                                <div class="col-lg-4 col-md-5">
                                    <div class="project-info">
                                        <ul>
                                            <li>
                                                <i class="icofont-ui-user"></i>
                                                <span>Client</span>
                                                <a href="https://{{ project.client.websiteUrl }}"> {{ project.client.companyName }} </a>
                                            </li>

                                            <li>
                                                <i class="icofont-laptop-alt"></i>
                                                <span>Start Date</span>
                                                {{ project.startDate | date('d/m/Y') }}
                                            </li>

                                            <li>
                                                <i class="icofont-checked"></i>
                                                <span>End Date</span>
                                                {{ project.endDate | date('d/m/Y') }}
                                            </li>

                                            <li>
                                                <i class="icofont-map-pins"></i>
                                                <span>Project State</span>
                                                {{ project.projectStatus | replace( {'_': ' '} ) | title}}
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- End Project Details Area -->

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
        
{% endblock %}